apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: votingApp
spec:
  selector:
    name: postgres-pod
    app: votingApp
  ports:
  - port: 5432
    targetPort: 5432
