apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: resultApp-deploy
    app: resultApp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resultApp-pod
      app: votingApp
  template:
    metadata:
      name: result-app-pod
      labels:
        name: resultApp-pod
        app: votingApp
    spec:
      containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
          - containerPort: 80
