apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: workerApp-deploy
    app: votingApp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: workerApp-pod
      app: votingApp
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: workerApp-pod
        app: votingApp
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1